#springboot日志格式
logging:
  pattern:
    console: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %line %clr(:){faint} %m%n'
#配置内置的activemq的队列
spring:
  artemis:
    embedded:
      queues: thanks

  jta:
    bitronix:
      #第一个数据源
      primary-datasource:
        datasource:
          max-pool-size: 5
          unique-name: bill
          class-name: com.mysql.cj.jdbc.MysqlXADataSource
          allow-local-transactions: true
          driver-properties:
            user: root
            password: '@gnnaa1993'
            url: 'jdbc:mysql://localhost/billing'
      #第二个数据源
      secondary-datasource:
        datasource:
          max-pool-size: 5
          unique-name: fruit
          class-name: com.mysql.cj.jdbc.MysqlXADataSource
          allow-local-transactions: true
          driver-properties:
            user: root
            password: '@gnnaa1993'
            url: 'jdbc:mysql://localhost:3307/fruit'
